version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '06:00'
      timezone: 'Europe/Berlin'
    rebase-strategy: disabled
    labels:
      - 'dependencies'
      - 'automerge'
      - "kodiak: merge.method = 'squash'"
    ignore:
      # Newer version get stuck when running with supertest in CircleCI
      - dependency-name: fetch-mock
        versions:
          - '> 9.11.0'
      - dependency-name: eslint
        versions:
          - '>= 10'
    groups:
      babel:
        patterns:
          - '@babel/*'
          - 'babel-*'
          - 'browserslist'
      eslint:
        patterns:
          - '@eslint-*'
          - '@eslint/*'
          - 'eslint-*'
          - 'eslint'
      jest:
        patterns:
          - '@jest/'
          - 'jest-*'
          - 'jest'
          - '@types/jest'
      laboperator-gmbh:
        patterns:
          - '@laboperator-gmbh/*'
